import { NextResponse } from "next/server";
import { guardAiRequest, toAiGuardErrorResponse } from "@/lib/wovo-ai/request-guard";
import { createSoraEditJob, createSoraJob } from "@/lib/wovo-ai/sora";
import { requireServerUser, supabaseServiceRoleRequest } from "@/lib/supabase/server";
import { asRecord, asString, extractVideoJobIdFromPath, isUuid } from "@/lib/wovo-ai/feed-utils";
import { resolveUserEmail } from "@/lib/wovo-ai/admin";
import { getSubscriptionStatus } from "@/lib/wovo-ai/subscription";
import { getEnv } from "@/lib/env";

type CreateVideoBody = {
  prompt?: string;
  durationSeconds?: number;
  remixMode?: "standard" | "animate_image" | "replace_dance";
  inputReferenceImage?: string;
  sourceOutputId?: string;
};

type VideoJobRow = {
  id: string;
  status: string;
  provider: string;
  provider_job_id: string | null;
  result_url: string | null;
  created_at: string;
};

type SourceGenerationRow = {
  id: string;
  input: Record<string, unknown>;
  output: Record<string, unknown>;
};

type SourceVideoJobRow = {
  id: string;
  status: string;
  provider_job_id: string | null;
};

type VideoRemixMode = "standard" | "animate_image" | "replace_dance";

const VIDEO_SOURCE_MODULES = new Set(["video_studio", "dance_remix"]);

function isCompletedVideoStatus(status: string): boolean {
  return ["completed", "success", "succeeded"].includes(status.trim().toLowerCase());
}

async function resolveSourceVideo(
  userId: string,
  sourceOutputId: string,
): Promise<{ sourceVideoJobId: string; sourceProviderVideoId: string }> {
  const generationRows = await supabaseServiceRoleRequest<SourceGenerationRow[]>(
    `/rest/v1/generations?select=id,input,output&id=eq.${encodeURIComponent(sourceOutputId)}&user_id=eq.${encodeURIComponent(userId)}&limit=1`,
  );
  const generation = generationRows?.[0];
  if (!generation) {
    throw new Error("Source video output not found.");
  }

  const input = asRecord(generation.input);
  const output = asRecord(generation.output);
  const outputExtra = asRecord(output.extra);
  const sourceModuleId = asString(input.module).trim();
  const sourceVideoPath = asString(output.video).trim();
  const sourceVideoJobId = asString(outputExtra.videoJobId).trim().toLowerCase();
  const sourcePathJobId = extractVideoJobIdFromPath(sourceVideoPath);

  if (!VIDEO_SOURCE_MODULES.has(sourceModuleId)) {
    throw new Error("Source output must be from a Wovo AI video module.");
  }
  if (asString(outputExtra.generatedBy).trim() !== "wovo_ai") {
    throw new Error("Source output must be generated by Wovo AI.");
  }
  if (!isUuid(sourceVideoJobId) || !sourcePathJobId || sourcePathJobId !== sourceVideoJobId) {
    throw new Error("Source output does not contain a valid Wovo video job.");
  }

  const sourceVideoRows = await supabaseServiceRoleRequest<SourceVideoJobRow[]>(
    `/rest/v1/video_jobs?select=id,status,provider_job_id&id=eq.${encodeURIComponent(sourceVideoJobId)}&user_id=eq.${encodeURIComponent(userId)}&limit=1`,
  );
  const sourceVideoJob = sourceVideoRows?.[0];
  if (!sourceVideoJob || !isCompletedVideoStatus(sourceVideoJob.status) || !sourceVideoJob.provider_job_id) {
    throw new Error("Source video is not ready yet. Wait for completion and try again.");
  }

  return {
    sourceVideoJobId: sourceVideoJob.id,
    sourceProviderVideoId: sourceVideoJob.provider_job_id,
  };
}

export async function POST(request: Request) {
  try {
    const { user } = await requireServerUser(request.headers.get("authorization"));
    const subscription = await getSubscriptionStatus(user.id, resolveUserEmail(user));
    const effectivePlan = (subscription.effective_plan ?? subscription.plan ?? "none").toString().toLowerCase();
    const hasProFeatureAccess =
      subscription.admin_access === true ||
      subscription.user_role === "admin" ||
      effectivePlan === "pro" ||
      effectivePlan === "business";

    if (!hasProFeatureAccess) {
      return NextResponse.json(
        { error: "AI Video Ad Studio and Dance Remix are Pro features. Upgrade to Pro to unlock video generation." },
        { status: 402 },
      );
    }

    if (getEnv("WOVO_VIDEO_GENERATION_ENABLED") !== "true") {
      return NextResponse.json(
        { error: "Video generation is not enabled because WOVO has not completed the current provider, metering, private-storage, and refund-path verification." },
        { status: 503 },
      );
    }

    const guard = await guardAiRequest(request.headers.get("authorization"), "video");
    const body = (await request.json().catch(() => ({}))) as CreateVideoBody;
    const prompt = body.prompt?.trim() ?? "";

    if (!prompt) {
      return NextResponse.json({ error: "Prompt is required." }, { status: 400 });
    }

    const remixModeRaw = (body.remixMode ?? "standard").trim().toLowerCase();
    if (!["standard", "animate_image", "replace_dance"].includes(remixModeRaw)) {
      return NextResponse.json({ error: "Invalid remix mode." }, { status: 400 });
    }

    const remixMode = remixModeRaw as VideoRemixMode;
    const sourceOutputId = body.sourceOutputId?.trim() ?? "";
    const inputReferenceImage = body.inputReferenceImage?.trim() ?? "";

    if (remixMode === "animate_image" && !inputReferenceImage) {
      return NextResponse.json({ error: "Upload an image to animate for this remix mode." }, { status: 400 });
    }

    if (remixMode === "replace_dance") {
      if (!sourceOutputId || !isUuid(sourceOutputId)) {
        return NextResponse.json({ error: "A valid source output is required for replace-dance mode." }, { status: 400 });
      }
    }

    const sourceVideo = remixMode === "replace_dance" ? await resolveSourceVideo(guard.userId, sourceOutputId) : null;

    const soraJob =
      remixMode === "replace_dance" && sourceVideo
        ? await createSoraEditJob({
            prompt,
            sourceProviderVideoId: sourceVideo.sourceProviderVideoId,
          })
        : await createSoraJob({
            prompt,
            durationSeconds: body.durationSeconds,
            inputReferenceImageUrl: remixMode === "animate_image" ? inputReferenceImage : undefined,
          });
    const provider = "sora";
    const providerJobId = soraJob.providerJobId;
    const providerStatus = soraJob.status;
    const providerResultUrl: string | null = null;
    const providerPayload = asRecord(soraJob.raw);

    const rows = await supabaseServiceRoleRequest<VideoJobRow[]>("/rest/v1/video_jobs?select=id,status,provider,provider_job_id,result_url,created_at", {
      method: "POST",
      headers: { Prefer: "return=representation" },
      body: JSON.stringify({
        user_id: guard.userId,
        provider,
        provider_job_id: providerJobId,
        prompt,
        status: providerStatus,
        result_url: providerResultUrl,
        result_payload: {
          ...providerPayload,
          remixMode,
          sourceOutputId: sourceOutputId || null,
          sourceVideoJobId: sourceVideo?.sourceVideoJobId ?? null,
          hasInputReferenceImage: remixMode === "animate_image" ? Boolean(inputReferenceImage) : false,
        },
      }),
    });

    const created = rows?.[0];
    return NextResponse.json({
      job: created ?? null,
      billing_source: guard.billingSource,
      trial_uses_remaining: guard.remainingTrialUses,
      warning: null,
    });
  } catch (error) {
    const guardResponse = toAiGuardErrorResponse(error);
    if (guardResponse) return guardResponse;
    return NextResponse.json(
      { error: error instanceof Error ? error.message : "Unable to create Sora video job." },
      { status: 500 },
    );
  }
}
